### ISSUE TITLE
request notification other than email

### ISSUE THREAD

**Issue by liomj** [GregMage/xmcontact#10]
i would like to suggest notification by Private Message to group or by using waiting module plugin https://github.com/XoopsModules25x/waiting

**Comment by GregMage** [comment]
It's a good idea, I'll integrate that into the next version.

**Comment by GregMage** [comment]
I finally integrated the plugin!
https://github.com/GregMage/xmcontact/commit/21e83f9eef7fde8ddd471188a1090c09acd595d4

**Comment by liomj** [comment]
Thank You @GregMage
