### ISSUE TITLE
Nouvelle fonctionnalité - Champs signature

### ISSUE THREAD

**Issue by alain01** [GregMage/xmcontact#12]
Bonjour Greg,
Ajouter lors de la création d'un formulaire un champs "signature"
Ainsi, lors de la réponse, on a une signature par défaut, sinon, le corps du texte est vide.

**Comment by GregMage** [comment]
A voir, mais ça serait lié au catégories?

**Comment by alain01** [comment]
Oui bien sur

**Comment by GregMage** [comment]
Intégré pour la version 2.0: https://github.com/GregMage/xmcontact/commit/20cc483a9d577b0cc27402123a48b86da5cb08ec
