### ISSUE TITLE
Nouvelle fonctionnalité : Affichage trié

### ISSUE THREAD

**Issue by alain01** [GregMage/xmcontact#14]
Possibilité d'avoir un tri sur les colonnes sur la page /modules/xmcontact/admin/request.php.

Quand on a beaucoup de formulaire, on pourrait vouloir afficher en 1er tout ceux qui ne sont pas répondu par exemple.
Ce n'est pas un filtre, "juste" un tri sur les colonnes.

**Comment by GregMage** [comment]
je vais ajouté 2 filtres, un pour les catégories et un pour les statuts
