### ISSUE TITLE
Nouvelle Fonctionnalité : Description courte / Description détaillée

### ISSUE THREAD

**Issue by alain01** [GregMage/xmcontact#15]
Hello,
sur la page index,
avoir la description courte des fiches contacts
et sur la page de la fiche contact concernée, avoir une description détaillée

Donc un champ de + dans la base données
Description devient description courte est n'est affiché que sur la page index
+
description détaillée (nouveau champs de la base de données) affichée sur la page de la fiche contact

**Comment by GregMage** [comment]
Merci pour la proposition mais après réflexion, cette option ne sera pas intégrée

**Comment by alain01** [comment]
Hey good news ! 
Happy day for me so !

**Comment by GregMage** [comment]
Intégré sans champ sup. Mais avec un délimitateur!

https://github.com/GregMage/xmcontact/commit/4f17e973439f5a44614a15a9332da5bfbbb9b1d7
