### ISSUE TITLE
Nouvelle fonctionnalité : possibilité de venir piocher une réponse préétablie

### ISSUE THREAD

**Issue by alain01** [GregMage/xmcontact#16]
Hello
Il serait intéressant de pouvoir ajouter un champs "réponse préenregistrée" et de se donner la possibilité de l'utiliser lors de la réponse, avec modification/ajout (de mots) en plus.

**Comment by GregMage** [comment]
C'est une fonctionnalité qui est compliquée, elle ouvre la porte à beaucoup de chose et il faudrait mieux définir le besoin. C'est une possibilité qui pourrait être implémentée dans une version futur si c'est vraiment intéressant

**Comment by alain01** [comment]
Explication :
Ajout d'une réponse à définir (titre + contenu)
Le titre va servir à l'intervenant qui peut choisir : 
- soit de répondre de façon manuelle
- soit de venir piocher dans une liste déroulante à choix unique parmi une liste de réponse pré-établie

S'il fait le choix d'une réponse prédéfinie, Il pourra ensuite ajouter du texte, si besoin.

Ex de réponse prédéfinie :
"Titre : Horaire"
"Contenu : 
Merci pour votre demande.
Nous vous rappelons que nos bureaux sont ouverts du Lundi au vendredi de 9h à 12h et de 14hà17h."

**Comment by GregMage** [comment]
J'ai intégré un système de réponse enregistrées, mais pas comme tu le décrit.

https://github.com/GregMage/xmcontact/commit/daa41370c75cb59689d3b36b57ecb63e53326fdb
