### ISSUE TITLE
Nouvelle fonctionnalité : possibilité de mémoriser la réponse

### ISSUE THREAD

**Issue by alain01** [GregMage/xmcontact#20]
Permettre de garder la réponse.

Ensuite d'autres options vont pouvoir apparaître pour étendre l'utilisation du module : 
- la réponse peut-être mémorisée dans un onglet "liste de réponses réutilisable"

**Comment by GregMage** [comment]
Le système est implanté!

https://github.com/GregMage/xmcontact/commit/1c4580fe79691a624baab80559ffdb9b7a18988f
