### ISSUE TITLE
Undefined array key "cat_id"

### ISSUE THREAD

**Issue by mambax7** [GregMage/xmcontact#24]
Warning: Undefined array key "cat_id" in file /xoops_data/caches/smarty_compile/da890def-xmcontact-xswatch4-default^%%05^050^050F7913%%db%3Axmcontact_form.tpl.php line 89

In /modules/xmcontact/admin/request.php:
Warning: Undefined array key "request_cid_options" in file /xoops_data/caches/smarty_compile/da890def-xmcontact-cp-default-default^%%46^46A^46AAA7D6%%db%3Axmcontact_admin_request.tpl.php line 32

XOOPS 2.5.11
PHP 8.0.7
xswatch4

**Comment by GregMage** [comment]
fixed: https://github.com/GregMage/xmcontact/commit/e9ac41db7b1e4c99ea5aa75e596b119bd1bed842
