### ISSUE TITLE
SmartyCompilerException

### ISSUE THREAD

**Issue by kostas4k** [GregMage/xmcontact#29]
In the latest version of xoops when I select (in admin) forms or request or in front page xmcontact from menu gives me: 

"Fatal error: Type of SmartyCompilerException::$line must be int (as in class Exception) in /path/to/xoops/root/class/libraries/vendor/smarty/smarty/libs/sysplugins/smartycompilerexception.php on line 8"

**Comment by GregMage** [comment]
Hello,

Can you test this version?

[https://github.com/GregMage/xmcontact/archive/refs/heads/master.zip](https://github.com/GregMage/xmcontact/archive/refs/heads/master.zip)

**Comment by kostas4k** [comment]
Everything looks good .. I start creating some forms for deeper checkup
