### ISSUE TITLE
Précisions pour le logo

### ISSUE THREAD

**Issue by cesagonchu** [GregMage/xmcontact#3]
Peux-tu préciser les extensions acceptées et le poids autorisé pour le logo des catégories ?
Voir image :
![xmcontactdemandes](https://cloud.githubusercontent.com/assets/4613970/16649944/d50c56f6-443b-11e6-8577-eddbd59d2519.gif)

**Comment by GregMage** [comment]
En travaillant sur ce point, j'ai découvert un gros bug sur mon code et dans xoops. Je travail sur la correction et j'ajoute cette fonctionnalité.

**Comment by cesagonchu** [comment]
Parfait, merci ;-)

**Comment by GregMage** [comment]
J'ai ajouté la taille mais pas les extensions, c'est les extensions logiques pour une image.
