### ISSUE TITLE
Db character set

### ISSUE THREAD

**Issue by kostas4k** [GregMage/xmcontact#6]
I think you should change the collation (db and stracture) from latin to utf8 because (in greek language) in category title and description only appears “???????”. I do it manuly via phpmyadmin and now works fine.

**Comment by GregMage** [comment]
Hello,
The module uses the XOOPS structure, the problem is with your installation. I can not change the characters.

**Comment by kostas4k** [comment]
Finally I realized that, this is a problem of my provider.
Every new module that I install has the same problem. Something that is not presented in the past. 
I'm sorry about that. You can close this and thanx for your work.

Costas

P.S. If you accept new features I can suggest some..

**Comment by alain01** [comment]
Hi Kostas4K,
yes, of course, he accepts ;-)

**Comment by GregMage** [comment]
No problem.
Thanks for your tests!
